services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mist
      POSTGRES_USER: casper
      POSTGRES_PASSWORD: casper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  uni-resolver-web:
    image: universalresolver/uni-resolver-web:latest
    ports:
      - "9050:8080"

  did-jwk-driver:
    image: transmute/restricted-resolver:latest
    ports:
      - "9051:8080"

  mist:
    image: mist:latest
    ports:
      - "9001:9001"
      - "9002:9002"
    depends_on:
      - redis
      - postgres
    environment:
      - MASTER_KEY=${MASTER_KEY}
      - POSTGRES_URL=postgres://casper:casper@postgres:5432/mist
      - REDIS_URL=redis://redis:6379
      - RESOLVER_HOST=https://dev.uniresolver.io/1.0/identifiers
      - DEVELOPMENT=true

volumes:
  postgres_data:
  redis_data:
