pkg-docs:
  - changed-files:
      - any-glob-to-any-file: docs/*
pkg-api:
  - changed-files:
      - any-glob-to-any-file: api/*
pkg-authn:
  - changed-files:
      - any-glob-to-any-file: authn/*
pkg-common:
  - changed-files:
      - any-glob-to-any-file: common/*
pkg-db:
  - changed-files:
      - any-glob-to-any-file: db/*
