repos:
  - repo: https://github.com/kykosic/pre-commit-rust
    rev: 0.4.0
    hooks:
      - id: cargo-fmt
      - id: cargo-clippy
      - id: cargo-check
  - repo: https://github.com/est31/cargo-udeps
    rev: v0.1.47
    hooks:
    - id: udeps
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.1
    hooks:
      - id: sqlfluff-fix
        args: [--dialect, postgres]
        exclude: crypt/schema.sql
        stages: [manual]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        stages: [manual]
