branch_whitelist = ["main"]

pre_bump_hooks = ["cargo set-version {{version}}"]
post_bump_hooks = ["git push", "git push origin {{version}}"]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "mist"
owner = "mist-id"
authors = [{ signature = "Danny Tatom", username = "its-danny" }]
