[package]
name = "common"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
axum = "0.7.5"
eyre = "0.6.12"
secstr = { version = "0.5.1", features = ["serde"] }
serde = { version = "1.0.209", features = ["derive"] }
sqlx = "0.8.2"
