[package]
name = "common"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
secstr = { version = "0.5.1", features = ["serde"] }
serde = { version = "1.0.209", features = ["derive"] }
