# fly.toml app configuration file generated for mist on 2024-09-13T08:00:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mist'
primary_region = 'sjc'

[build]
image = 'mist'

[http_service]
internal_port = 9002
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
